sudo: false
language: generic

cache:
  directories:
    - $HOME/.stack

install:
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --version

script:
  - stack build
  - stack install
  - stack test

matrix:
  include:
   - os: linux
   - os: osx
